"""empty message

Revision ID: 19b995f85dcb
Revises: 
Create Date: 2024-05-17 21:34:40.631177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b995f85dcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('displayname', sa.String(length=150), nullable=False),
    sa.Column('emailaddress', sa.String(length=150), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('room',
    sa.Column('roomId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('documentId', sa.String(), nullable=True),
    sa.Column('ownerId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('roomId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('user')
    # ### end Alembic commands ###
